/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.examples.orderservice;

import com.example.orderservice.OrderPbEntity;
import com.example.orderservice.OrderServiceGrpc;
import io.grpc.*;

public class App {

    public static void main(String[] args) {
        ManagedChannel managedChannel = ManagedChannelBuilder.forAddress("localhost",10082)
                .usePlaintext()
                .build();
        Channel channel = ClientInterceptors.intercept(managedChannel, new ClientInterceptor() {
            @Override
            public <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(MethodDescriptor<ReqT, RespT> method, CallOptions callOptions, Channel next) {
                System.out.println("method:"+method.getFullMethodName());
                return next.newCall(method,callOptions);
            }
        });
        OrderServiceGrpc.OrderServiceBlockingStub orderServiceBlockingStub = OrderServiceGrpc.newBlockingStub(channel);

        OrderPbEntity.GetOrderListReq req = OrderPbEntity.GetOrderListReq.newBuilder().setUserId("1")
                .build();
        OrderPbEntity.GetOrderListRes orderList = orderServiceBlockingStub.getOrderList(req);
        for (String orderId : orderList.getOrderIdsList()) {
            System.out.println("orderId:"+orderId);
        }

    }
}
