/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.payservice;

import io.grpc.*;
import io.grpc.stub.MetadataUtils;

import java.util.UUID;

public class App {

    public static void main(String[] args) {
        ManagedChannel channel = ManagedChannelBuilder.forAddress("localhost",10083)
                .usePlaintext()
                .build();
        Metadata metadata = new Metadata();
        metadata.put( Metadata.Key.of("token",Metadata.ASCII_STRING_MARSHALLER), UUID.randomUUID().toString().replaceAll("-",""));
        Channel headChannel = ClientInterceptors.intercept(channel, MetadataUtils.newAttachHeadersInterceptor(metadata));
        PayServiceGrpc.PayServiceBlockingStub payServiceBlockingStub = PayServiceGrpc.newBlockingStub(headChannel);
        PayServicePbEntity.payOrderRes res = payServiceBlockingStub.payOrder(PayServicePbEntity.payOrderReq.newBuilder().setOrderId("order_1")
                .build());
        System.out.println("resCode:"+res.getRetCode()+"\tresMsg:"+res.getRetMsg());
    }
}
