/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.examples.easyservice;

import com.examples.easyservice.impl.EasyServiceImpl;
import com.examples.easyservice.registry.NacosRegistryBuild;
import io.grpc.Server;
import io.grpc.netty.NettyServerBuilder;

import java.io.IOException;
import java.net.URI;

public class App {

    public static final int grpcPort = 10087;


    public static void main(String[] args) throws InterruptedException, IOException {
        URI uri = URI.create("http://localhost:8848");
        if (1==1 && 1==2?true:false){

        }
        for (int i = 0; i < 3; i++) {
            int finalI = i;
            new Thread(()->{
                EasyServiceImpl easyService = new EasyServiceImpl(grpcPort + finalI);
                Server server = NettyServerBuilder.forPort(grpcPort + finalI).addService(easyService)
                        .build();
                try {
                    server.start();
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }

                NacosRegistryBuild build = new NacosRegistryBuild(uri,grpcPort+ finalI,new EasyServiceImpl[]{easyService} );
                build.init();
                try {
                    server.awaitTermination();
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                }

            }).start();

        }

    }
}
