/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

import com.example.userinfoservice.MainApplication;
import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        MainApplication classUnderTest = new MainApplication();
    }
}
