// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: blendservice.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *BlendReq) Reset() {
	*x = BlendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blendservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlendReq) ProtoMessage() {}

func (x *BlendReq) ProtoReflect() protoreflect.Message {
	mi := &file_blendservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlendReq.ProtoReflect.Descriptor instead.
func (*BlendReq) Descriptor() ([]byte, []int) {
	return file_blendservice_proto_rawDescGZIP(), []int{0}
}

func (x *BlendReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BlendRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nid []string `protobuf:"bytes,1,rep,name=nid,proto3" json:"nid,omitempty"`
}

func (x *BlendRes) Reset() {
	*x = BlendRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blendservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlendRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlendRes) ProtoMessage() {}

func (x *BlendRes) ProtoReflect() protoreflect.Message {
	mi := &file_blendservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlendRes.ProtoReflect.Descriptor instead.
func (*BlendRes) Descriptor() ([]byte, []int) {
	return file_blendservice_proto_rawDescGZIP(), []int{1}
}

func (x *BlendRes) GetNid() []string {
	if x != nil {
		return x.Nid
	}
	return nil
}

var File_blendservice_proto protoreflect.FileDescriptor

var file_blendservice_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x61, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x22, 0x0a, 0x08, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x1c, 0x0a, 0x08, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x6e,
	0x69, 0x64, 0x32, 0x43, 0x0a, 0x0c, 0x42, 0x6c, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x33, 0x0a, 0x05, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x12, 0x14, 0x2e, 0x70, 0x61,
	0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x14, 0x2e, 0x70, 0x61, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x62,
	0x6c, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x42, 0x35, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x61, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x42, 0x12, 0x50, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x62, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x80, 0x01, 0x01, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blendservice_proto_rawDescOnce sync.Once
	file_blendservice_proto_rawDescData = file_blendservice_proto_rawDesc
)

func file_blendservice_proto_rawDescGZIP() []byte {
	file_blendservice_proto_rawDescOnce.Do(func() {
		file_blendservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_blendservice_proto_rawDescData)
	})
	return file_blendservice_proto_rawDescData
}

var file_blendservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blendservice_proto_goTypes = []interface{}{
	(*BlendReq)(nil), // 0: payservice.blendReq
	(*BlendRes)(nil), // 1: payservice.blendRes
}
var file_blendservice_proto_depIdxs = []int32{
	0, // 0: payservice.BlendService.blend:input_type -> payservice.blendReq
	1, // 1: payservice.BlendService.blend:output_type -> payservice.blendRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blendservice_proto_init() }
func file_blendservice_proto_init() {
	if File_blendservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blendservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blendservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlendRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blendservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blendservice_proto_goTypes,
		DependencyIndexes: file_blendservice_proto_depIdxs,
		MessageInfos:      file_blendservice_proto_msgTypes,
	}.Build()
	File_blendservice_proto = out.File
	file_blendservice_proto_rawDesc = nil
	file_blendservice_proto_goTypes = nil
	file_blendservice_proto_depIdxs = nil
}
